version: "3"
services:
    mongodb:
        image: mongo
        ports: 
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example
        volumes:
            - mongo-data:/data/db
    mongoexp:
        image: mongo-express
        ports:
            - 8080:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=example
            - ME_CONFIG_MONGODB_SERVER=mongodb
    lambda:
        image: lambci/lambda:python3.6
        ports: 
            - 9001:9001
        environment: 
            - DOCKER_LAMBDA_STAY_OPEN=1
        volumes: 
            - ./pythonlambda:/var/task
volumes:
    mongo-data:
        driver: local
